feature(zjow): Add Lighttuner demo for Tianshou
opendilab/LightTuner pull request #5
Opened 2022-09-07 12:09 UTC by zjowowen

2022-09-13 04:08 UTC, HansBug requested changes

2022-09-13 04:08 UTC, HansBug commented on template/tianshou_cartpole_dqn_config.py
> +import torch, numpy as np
import请分开，不要在一行上开多个

2022-09-13 04:08 UTC, HansBug commented on template/tianshou_cartpole_dqn_config.py
> +import tianshou as ts
这里建议确认下，是否tianshou也被约定俗成地导入为`ts`（类似`numpy`一般被导入为`np`、`pandas`一般为`pd`），如果不是的话建议改回`import tianshou`以方便理解。

2022-09-13 04:08 UTC, HansBug commented on demo/scheduler_demo.py
> +    dirname = os.path.abspath('./template')
换个名，我记得dirname是个保留字

2022-09-13 04:08 UTC, HansBug commented on demo/scheduler_demo.py
> +    hpo_info = {'policy': {'learning_rate': uniform(1e-3, 2e-3)}}
这里我看了下，没有在其他地方使用，因此建议直接放进`.spaces()`里面即可。

2022-09-13 04:08 UTC, HansBug commented on demo/scheduler_demo.py
> +    scheduler.stop()
另外关于scheduler有个建议，是否考虑给scheduler弄一个`__enter__`、`__exit__`机制，以便使用`with`来创建上下文，并通过`finally`来确保资源一定能被释放。目前这里的写法存在资源释放失败的可能性（比如中间的hpo环节出错）

2022-09-20 08:45 UTC, zjowowen commented on template/tianshou_cartpole_dqn_config.py
> +import torch, numpy as np
fixed.

2022-09-20 08:45 UTC, zjowowen commented on template/tianshou_cartpole_dqn_config.py
> +import tianshou as ts
fixed.

2022-09-20 08:45 UTC, zjowowen commented on demo/scheduler_demo.py
> +    hpo_info = {'policy': {'learning_rate': uniform(1e-3, 2e-3)}}
fixed.

2022-09-20 08:46 UTC, zjowowen commented on demo/scheduler_demo.py
> +    scheduler.stop()
fixed.

2022-09-20 08:46 UTC, zjowowen commented on demo/scheduler_demo.py
> +    dirname = os.path.abspath('./template')
fixed.

2022-09-20 10:57 UTC, PaParaZz1 approved these changes

2022-09-20 10:58 UTC, merged